"""Pydantic schemas for the SmartReco API."""
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class FileIdRequest(BaseModel):
    """Simple request containing a dataset identifier."""

    file_id: str = Field(..., description="Identifier returned by /upload")


class ColumnSummary(BaseModel):
    """Summary of a column for preview purposes."""

    name: str
    dtype: str
    non_nulls: int
    unique: int
    sample_values: List[Any]


class DatasetPreviewResponse(BaseModel):
    """Preview of the uploaded dataset."""

    file_id: str
    rows: List[Dict[str, Any]]
    dtypes: Dict[str, str]
    columns: List[ColumnSummary]


class UploadResponse(DatasetPreviewResponse):
    """Response after uploading a file."""

    original_filename: str


class AnalyzeResponse(BaseModel):
    """Full dataset analysis generated by the agent."""

    file_id: str
    column_types: Dict[str, str]
    descriptive_stats: Dict[str, Any]
    correlation_insights: List[Dict[str, Any]]
    suggested_plots: List[Dict[str, Any]]
    dataset_overview: Dict[str, Any]


class PlotRequest(FileIdRequest):
    """Request to generate plots for the dataset."""

    plot_types: Optional[List[str]] = Field(
        default=None, description="Optional subset of plot types to generate."
    )


class PlotResult(BaseModel):
    """A generated plot encoded as base64."""

    title: str
    plot_type: str
    image_base64: str
    description: Optional[str] = None


class PlotResponse(BaseModel):
    """Collection of generated plots."""

    file_id: str
    plots: List[PlotResult]


class FeatureSuggestion(BaseModel):
    """Description of a proposed feature engineering step."""

    name: str
    description: str
    columns: List[str]
    preview: Optional[Dict[str, Any]] = None


class FeatureResponse(BaseModel):
    """Suggested features for a dataset."""

    file_id: str
    suggestions: List[FeatureSuggestion]


class RuleCandidate(BaseModel):
    """Business rule candidate extracted heuristically."""

    rule: str
    rationale: str
    severity: str


class RuleResponse(BaseModel):
    """List of extracted business rules."""

    file_id: str
    rules: List[RuleCandidate]


class RecommendationItem(BaseModel):
    """Single recommendation or action item."""

    title: str
    description: str
    priority: str


class RecommendationResponse(BaseModel):
    """Agent-generated recommendations."""

    file_id: str
    insights: str
    business_rules: List[RuleCandidate]
    actions: List[RecommendationItem]



