"""Pydantic schemas for the SmartReco API."""
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class FileIdRequest(BaseModel):
    """Simple request containing a dataset identifier."""

    file_id: str = Field(..., description="Identifier returned by /upload")


class ColumnSummary(BaseModel):
    """Summary of a column for preview purposes."""

    name: str
    dtype: str
    non_nulls: int
    unique: int
    sample_values: List[Any]


class DatasetPreviewResponse(BaseModel):
    """Preview of the uploaded dataset."""

    file_id: str
    rows: List[Dict[str, Any]]
    dtypes: Dict[str, str]
    columns: List[ColumnSummary]


class UploadResponse(DatasetPreviewResponse):
    """Response after uploading a file."""

    original_filename: str
    delimiter: str | None = None
    has_header: bool | None = None
    created_at: Optional[str] = None


class AnalyzeResponse(BaseModel):
    """Full dataset analysis generated by the agent."""

    file_id: str
    column_types: Dict[str, str]
    descriptive_stats: Dict[str, Any]
    correlation_insights: List[Dict[str, Any]]
    suggested_plots: List[Dict[str, Any]]
    dataset_overview: Dict[str, Any]
    quality_issues: Optional[List[Dict[str, Any]]] = None


class PlotRequest(FileIdRequest):
    """Request to generate plots for the dataset."""

    plot_types: Optional[List[str]] = Field(
        default=None, description="Optional subset of plot types to generate."
    )


class PlotResult(BaseModel):
    """A generated plot encoded as base64."""

    title: str
    plot_type: str
    image_base64: str
    description: Optional[str] = None


class PlotResponse(BaseModel):
    """Collection of generated plots."""

    file_id: str
    plots: List[PlotResult]


class FeatureSuggestion(BaseModel):
    """Description of a proposed feature engineering step."""

    name: str
    description: str
    columns: List[str]
    preview: Optional[Dict[str, Any]] = None


class FeatureResponse(BaseModel):
    """Suggested features for a dataset."""

    file_id: str
    suggestions: List[FeatureSuggestion]


class RuleCandidate(BaseModel):
    """Business rule candidate extracted heuristically."""

    rule: str
    rationale: str
    severity: str


class RuleResponse(BaseModel):
    """List of extracted business rules."""

    file_id: str
    rules: List[RuleCandidate]


class RecommendationItem(BaseModel):
    """Single recommendation or action item."""

    title: str
    description: str
    priority: str


class RecommendationResponse(BaseModel):
    """Agent-generated recommendations."""

    file_id: str
    insights: str
    business_rules: List[RuleCandidate]
    actions: List[RecommendationItem]


class DatasetMeta(BaseModel):
    """Metadata for persisted datasets."""

    file_id: str
    name: str
    rows: int
    columns: int
    created_at: str
    updated_at: Optional[str] = None
    delimiter: Optional[str] = None
    encoding: Optional[str] = None
    has_header: Optional[bool] = None


class DatasetListResponse(BaseModel):
    datasets: List[DatasetMeta]


class DrilldownRequest(FileIdRequest):
    """Request slice for drilldown coming from a graph click."""

    column: str
    values: Optional[List[Any]] = None
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    limit: int = 200


class DrilldownResponse(BaseModel):
    file_id: str
    column: str
    count: int
    stats: Dict[str, Any]
    rows: List[Dict[str, Any]]


class TemplateDescriptor(BaseModel):
    id: str
    name: str
    description: str
    layout: Dict[str, Any]


class TemplatesResponse(BaseModel):
    templates: List[TemplateDescriptor]


class RuleConfigRequest(FileIdRequest):
    """Request to update rule thresholds/weights."""

    weights: Dict[str, float] = Field(default_factory=dict)
    thresholds: Dict[str, float] = Field(default_factory=dict)
    multipliers: Dict[str, float] = Field(default_factory=dict)


class HealthResponse(BaseModel):
    status: str
    dataset_loaded: bool
    last_file_id: Optional[str] = None
    dataset_count: int = 0
    rules_loaded: int = 0
    scored_count: int = 0





